image: jakzal/phpqa:php8.1

before_script:
  - composer install

cache:
  paths: 
      - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

phpcs:
  stage: CodingStandards
  script:
      - phpcs -v --standard=@PSR1 --ignore=./src/Kernel.php ./src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
      - phpstan analyse ./src
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
      - php bin/phpunit
  allow_failure: false