image: jakzal/phpqa:php8.1

before_script:
  - cd ApiLibrary && composer install

cache:
  paths: 
      - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

phpcs:
  stage: CodingStandards
  script:
      - phpcs -v --standard=PSR1 --ignore=./ApiLibrary/src/Kernel.php ./ApiLibrary/src
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
      - cd ApiLibrary && php bin/phpunit
  allow_failure: false