image: jakzal/phpqa:php8.1

before_script:
  - composer install

cache:
  paths: 
      - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
      - local-php-security-checker  --path=./ApiLibrary/composer.lock
  allow_failure: false

phpcs:
  stage: CodingStandards
  script:
      - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./ApiLibrary/src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
      - phpstan analyse ./ApiLibrary/src
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
      - php bin/phpunit
  allow_failure: false