image: jakzal/phpqa:php8.1

before_script:
  - cd ApiLibrary && composer install

cache:
  paths: 
      - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
      - local-php-security-checker  --path=./composer.lock
  allow_failure: false

phpcs:
  stage: CodingStandards
  script:
      - phpcs -v --standard=PSR1 --ignore=./src/Kernel.php ./src
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
      - php bin/phpunit
  allow_failure: false