nelmio_api_doc:
    models:
        names:
            - { alias: ReaderInfos, type: App\Entity\Reader, groups: [reader_infos] }
            - { alias: BookInfos, type: App\Entity\Book, groups: [book_infos] }
    documentation:
        info:
            title: Library
            description: Find a Book !
            version: 1.0.0
        components:
            schemas:
                BookBorrow:
                    properties:
                        book:
                            ref: "#/components/schemas/BookInfos"
                        dateBorrow:
                            type: date
                            example: '2023-03-24T00:00:00+01:00'
                        dateReturn:
                            type: date
                            example: '2023-03-24T00:00:00+01:00'
                        author:
                            type: string
                            example: 'John Doe'
                BookAuthors:
                    properties:
                        book:
                            ref: "#/components/schemas/BookInfos"
                        author:
                            type: string
                            example: 'JK Rowling'
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
